### ISSUE TITLE
Possible Code Optimisation

### ISSUE THREAD

**Issue by KyleCotton** [Jordan-Kennedy/Jordan-Kennedy.Github.io#2]
Suggestion for your code. Have you thought about using PHP so that the menu code doesn't have to be repeated. Try [Using PHP for menu navigation](http://www.apaddedcell.com/how-automatically-include-your-header-navigation-and-footer-every-page).

**Comment by Jordan-Kennedy** [comment]
I had not no, although after doing a tad bit of research it appears that github can only serve web client content and not any back end technology that could be used to manipulate technology. so php is a no go unfortunately.
